export default function LeftSidebar() {
    return (
        <div className="row-span-4 p-4 border-1 border-black rounded-md overflow-auto">
            <h2 className="text-xl font-bold mb-3">BIT 簡介</h2>
            <p className="text-lg mb-2">
                Binary Indexed Tree（BIT），又稱樹狀數組或 Fenwick Tree，是一種高效的資料結構，
                主要用於處理數列中的區間總和查詢（Prefix Sum）與單點更新操作。
            </p>
            <p className="text-lg mb-2">
                相比傳統前綴和陣列無法支援動態修改，BIT 能夠在 O(log n) 時間內完成更新與查詢，
                是競賽與系統優化中常見的利器。
            </p>
            <p className="text-lg">
                其核心概念是透過陣列與二進位運算的結合，巧妙儲存部分區間的總和，
                使每次操作只需訪問少數幾個節點。
            </p>
            <div className="text-base text-right mt-2 text-gray-600">
                (Generated by ChatGPT)
            </div>
        </div>
    );
}